In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

In [2]:
a=np.array([1,0,0]*4)

In [3]:
a

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [4]:
A1=np.vstack((a,np.roll(a,1),np.roll(a,2)))

In [5]:
A1

array([[1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [6]:
s=np.array([480,650,580,390])

In [7]:
A2=A1*np.repeat(s,3)

In [8]:
A2

array([[480,   0,   0, 650,   0,   0, 580,   0,   0, 390,   0,   0],
       [  0, 480,   0,   0, 650,   0,   0, 580,   0,   0, 390,   0],
       [  0,   0, 480,   0,   0, 650,   0,   0, 580,   0,   0, 390]])

In [10]:
a1=np.zeros(12)
a1[:3]=1
a1

array([1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
A3=np.vstack((a1,np.roll(a1,3),np.roll(a1,6),np.roll(a1,9)))
A3

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [12]:
A=np.vstack((A1,A2,A3))
A

array([[  1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,
          0.],
       [  0.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,
          0.],
       [  0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,
          1.],
       [480.,   0.,   0., 650.,   0.,   0., 580.,   0.,   0., 390.,   0.,
          0.],
       [  0., 480.,   0.,   0., 650.,   0.,   0., 580.,   0.,   0., 390.,
          0.],
       [  0.,   0., 480.,   0.,   0., 650.,   0.,   0., 580.,   0.,   0.,
        390.],
       [  1.,   1.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [  0.,   0.,   0.,   1.,   1.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   1.,   1.,   1.,   0.,   0.,
          0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   1.,
          1.]])

In [13]:
masses=np.array([10,16,8])
spaces=np.array([6800,8700,5300])
goods=np.array([18,15,23,12])
b=np.hstack((masses,spaces,goods))

In [14]:
b

array([  10,   16,    8, 6800, 8700, 5300,   18,   15,   23,   12])

In [15]:
money=np.array([3100,3800,3500,2800])
c=np.repeat(money,3)
c

array([3100, 3100, 3100, 3800, 3800, 3800, 3500, 3500, 3500, 2800, 2800,
       2800])

In [16]:
ans=sp.optimize.linprog(-c,A,b)

In [18]:
-ans.fun

121363.15789473493

In [19]:
ans.x

array([ 0.        ,  0.        ,  0.        , 10.        ,  0.        ,
        5.        ,  0.        , 12.94736842,  3.        ,  0.        ,
        3.05263158,  0.        ])